import{i as l,S as i}from"./assets/vendor-0fc460d7.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=n(e);fetch(e.href,o)}})();function c(t,r,n){l.show({iconUrl:t,titleColor:"White",titleSize:"24px",message:r,messageColor:"White",messageSize:"16px",backgroundColor:n,position:"topRight",timeout:3e3})}function u(){document.querySelector(".loader").classList.remove("visually-hidden")}function d(){document.querySelector(".loader").classList.add("visually-hidden")}function f(){const t=document.querySelector(".gallery");t.innerHTML=""}function p(t){return document.querySelector(".gallery"),t.map(r=>`<li class="gallery-item">
    <a href="${r.largeImageURL}" data-lightbox="gallery-link">
      <img class="gallery-image" src="${r.webformatURL}" alt="${r.tags}">
    </a>
    <div class="gallery-info">
      <p><b>Likes:</b> ${r.likes}</p>
      <p><b>Views:</b> ${r.views}</p>
      <p><b>Comments:</b> ${r.comments}</p>
      <p><b>Downloads:</b> ${r.downloads}</p>
    </div></li>
  `).join("")}function y(t){const r="43325485-b0026802577d8a210f4fcd054",s=`https://pixabay.com/api/?${new URLSearchParams({key:r,q:t,image_type:"photo",orientation:"horizontal",safesearch:!0})}`;return fetch(s).then(e=>{if(!e.ok)throw new Error(e.status);return e.json()})}const m="/goit-js-hw-11/assets/bi_x-octagon-06de2d57.svg",h=document.querySelector(".form");document.querySelector(".text-input");const g=document.querySelector("gallery"),b=new i("#gallery-link",{captions:!0,captionDelay:250,captionsData:"alt",captionPosition:"bottom"});h.addEventListener("submit",L);function L(t){t.preventDefault();const r=t.currentTarget.search.value.trim();u(),f(),y(r).then(n=>{if(n.results&&n.results.length===0)c(m,"Sorry, there are no images matching your search query. Please try again!","#ef4040");else{const s=p(n.results);s?(g.innerHTML=s,b.refresh()):console.error("Error: createGalleryMarkup returned undefined or not an array.")}}).catch(n=>{console.error("Error:",n)}).finally(()=>{d()})}
//# sourceMappingURL=commonHelpers.js.map
